export const USER_LOGIN_REQUEST: string = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS: string = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL: string = "USER_LOGIN_FAIL";

export const USER_LOGOUT: string = "USER_LOGOUT";

export const USER_REGISTER_REQUEST: string = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS: string = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL: string = "USER_REGISTER_FAIL";

export const USER_DETAILS_REQUEST: string = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS: string = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL: string = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET: string = "USER_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST: string =
    "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS: string =
    "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL: string = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET: string = "USER_UPDATE_PROFILE_RESET";
