# Generated by Django 4.1.6 on 2023-02-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_old_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInStock',
            new_name='count_in_stock',
        ),
    ]
