# Generated by Django 4.1.6 on 2023-02-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
